before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: XS1gQENffVx36HR+b5/kuGKgtQy0JL6oqcV3rr5FP407+ifrhnurZX84EqLlLFflI5hwonOD3gu/v5AkhZhvhJSc7/dDEHeS+3NgQveAM6KP7957Tn1o9qCfT19u5oihT+p1PrcU6r9RzSTz8wWFEYxrJ1nzwbfzjo1c2OxVvbxjcT0YS6F6DlQI6/Cm780vSAc17GLLGxGmrUr39hRvGwrlex7hq/C+mfImQ4LRwiQIgdnXM9wiLdhCIP27LTaCWHWD4447DjIbQM8/jmkzMh1iEUG9am5AsFxpzVsiuRotLBM7/tMavm2+scgMooaozW8mTCG2xfYd7HuB03MDutdK9+MjWBhAvKBip+5mEx1S8kNUFINguZTsMMgAJ0d8RmirPYJI4ZwK8C3cmsPilFIVOMM3xHxqn7sHmvMkZqF0iZwl92hgVHiu2RowsirKOxFTXX0olEfu3aQGBRhM7xVn5LAgifcs5YKAex1I+YF/RdrF9wNYmdYaH+7fsEB3fFuB5qZkDuHSDC0MBmpPaRvTHnX+rLJDKotkn2NpZVNWHPrEW9q2VAxZGJcPwNM6pX8iefEigoIajpHOCGoerVJ1ApKSMU/Yfrd9KJEpJ80U9y8fiTRwqFkcOwbQ7TlVaMttz38yL2rzl2+gYnraYQ49Hlj7LN+Cp5AyYCj7ezk= # CRYPTO_AES_KEY
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
